# url: apieconomyhacklab.github.io
# baseurl: /buildfordevelopers

# Site settings
title: Build for Developers
email: jarkko@vimo.fi
description: "Book about Application Developers as Customers in API Economy. To be published 2019. Author Jarkko Moilanen (PhD)"


page:
- title: Build for Developers 

# Team names, titles and social links
people:
- name: Jarkko Moilanen
  pic: 1
  position: Book author
  social:
    - title: twitter
      url: https://twitter.com/kyyberi
    - title: linkedin
      url: https://www.linkedin.com/in/jarkkomoilanen/
    - title: github
      url: https://github.com/kyyberi/

- name: Viljami Kuosmanen
  pic: 2
  position: Developer (Advisory Board)
  social:
    - title: twitter
      url: https://twitter.com/anttiviljami
    - title: linkedin
      url: https://www.linkedin.com/in/anttiviljami/
    - title: github
      url: https://github.com/anttiviljami/

- name: Jani Karhunen
  pic: 3
  position: Developer (Advisory Board)
  social:
    - title: twitter
      url: https://twitter.com/janikarh/
    - title: linkedin
      url: https://www.linkedin.com/in/janikarhunen/
    - title: github
      url: https://github.com/janikarh

- name: Your name here?
  pic: 4
  position: Developer (Advisory Board)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/kyyberi
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
